/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.PlanesTuristicos;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author josem
 */
public class AgregarPlan extends javax.swing.JFrame {
    
    int mousex, mousey;
    private PlanesTuristicos myPlan;
    private InicioEmpresa inicioEmpresa;
    /**
     * Creates new form AgregarPlan
     */
    public AgregarPlan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelVolver = new javax.swing.JPanel();
        jLabelVolver = new javax.swing.JLabel();
        jPanelRegistrar = new javax.swing.JPanel();
        jLabelRegistrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparatorName = new javax.swing.JSeparator();
        labelUsuario = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        labelEdad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescrip = new javax.swing.JTextArea();
        Header = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel4.setText("Agregar Plan Turistico");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabelVolver.setBackground(new java.awt.Color(0, 0, 0));
        jLabelVolver.setFont(new java.awt.Font("Quicksand Light", 1, 18)); // NOI18N
        jLabelVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVolver.setText("Volver");
        jLabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelVolverLayout = new javax.swing.GroupLayout(jPanelVolver);
        jPanelVolver.setLayout(jPanelVolverLayout);
        jPanelVolverLayout.setHorizontalGroup(
            jPanelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelVolverLayout.setVerticalGroup(
            jPanelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 110, 40));

        jLabelRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        jLabelRegistrar.setFont(new java.awt.Font("Quicksand Light", 1, 18)); // NOI18N
        jLabelRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrar.setText("Registrar");
        jLabelRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarLayout = new javax.swing.GroupLayout(jPanelRegistrar);
        jPanelRegistrar.setLayout(jPanelRegistrarLayout);
        jPanelRegistrarLayout.setHorizontalGroup(
            jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRegistrarLayout.setVerticalGroup(
            jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanelRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ImagenAgregarPlan.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 340, 530));

        labelNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombre");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        txtName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.setText("Ingrese Nombre");
        txtName.setBorder(null);
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked1(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 330, -1));

        jSeparatorName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparatorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        labelUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario.setText("Precio");
        jPanel1.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecio.setText("Ingrese Usuario");
        txtPrecio.setBorder(null);
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrecioMouseClicked1(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 450, -1));

        labelEdad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEdad.setText("Descripccion");
        jPanel1.add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 460, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 460, 10));

        txtaDescrip.setColumns(20);
        txtaDescrip.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtaDescrip.setForeground(new java.awt.Color(102, 102, 102));
        txtaDescrip.setRows(5);
        txtaDescrip.setText("Ingrese la descripccion");
        txtaDescrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtaDescripMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtaDescripMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtaDescrip);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 460, 150));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 460, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        if(txtName.getText().equals("Ingrese Nombre")){
            txtName.setText("");
            txtName.setForeground(Color.BLACK);
        }
        if(txtPrecio.getText().isEmpty()){
            txtPrecio.setText("Ingrese Precio");
            txtPrecio.setForeground(Color.GRAY);
        }
        if(txtaDescrip.getText().isEmpty()){
            txtaDescrip.setText("Ingrese Edad");
            txtaDescrip.setForeground(Color.GRAY);
        }
        
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtNameMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked1
        if(txtName.getText().equals("Ingrese Nombre")){
            txtName.setText("");
            txtName.setForeground(Color.BLACK);
        }
        if(txtPrecio.getText().isEmpty()){
            txtPrecio.setText("Ingrese Usuario");
            txtPrecio.setForeground(Color.GRAY);
        }
        if(txtaDescrip.getText().isEmpty()){
            txtaDescrip.setText("Ingrese Edad");
            txtaDescrip.setForeground(Color.GRAY);
        }
        
    }//GEN-LAST:event_txtNameMouseClicked1

    private void txtPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMouseClicked
        if(txtName.getText().isEmpty()){
            txtName.setText("Ingrese Nombre");
            txtName.setForeground(Color.GRAY);
        }
        if(txtPrecio.getText().equals("Ingrese Usuario")){
            txtPrecio.setText("");
            txtPrecio.setForeground(Color.BLACK);
        }
        if(txtaDescrip.getText().isEmpty()){
            txtaDescrip.setText("Ingrese Edad");
            txtaDescrip.setForeground(Color.GRAY);
        }
        
    }//GEN-LAST:event_txtPrecioMouseClicked

    private void txtPrecioMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMouseClicked1
        if(txtName.getText().isEmpty()){
            txtName.setText("Ingrese Nombre");
            txtName.setForeground(Color.GRAY);
        }
        if(txtPrecio.getText().equals("Ingrese Usuario")){
            txtPrecio.setText("");
            txtPrecio.setForeground(Color.BLACK);
        }
        if(txtaDescrip.getText().isEmpty()){
            txtaDescrip.setText("Ingrese Edad");
            txtaDescrip.setForeground(Color.GRAY);
        }
        
    }//GEN-LAST:event_txtPrecioMouseClicked1

    private void txtaDescripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtaDescripMouseClicked
        if(txtName.getText().isEmpty()){
            txtName.setText("Ingrese Nombre");
            txtName.setForeground(Color.GRAY);
        }
        if(txtPrecio.getText().isEmpty()){
            txtPrecio.setText("");
            txtPrecio.setForeground(Color.GRAY);
        }
        if(txtaDescrip.getText().equals("Ingrese la descripccion")){
            txtaDescrip.setText("");
            txtaDescrip.setForeground(Color.BLACK);
        }
        
        
        
    }//GEN-LAST:event_txtaDescripMouseClicked

    private void txtaDescripMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtaDescripMousePressed
        if(txtName.getText().isEmpty()){
            txtName.setText("Ingrese Nombre");
            txtName.setForeground(Color.GRAY);
        }
        if(txtPrecio.getText().isEmpty()){
            txtPrecio.setText("");
            txtPrecio.setForeground(Color.BLACK);
        }
        if(txtaDescrip.getText().equals("Ingrese la descripccion")){
            txtaDescrip.setText("Ingrese la descripccion");
            txtaDescrip.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtaDescripMousePressed

    private void jLabelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarMouseClicked
        String name = txtName.getText();
        String price = txtPrecio.getText();
        String desc = txtaDescrip.getText();
        
        try{
            myPlan.addPlan(name,InicioEmpresa.nombreEmpresa,desc,price);
            JOptionPane.showMessageDialog(null,"Plan turistico enviado exitosamente");
            inicioEmpresa = new InicioEmpresa();
            inicioEmpresa.setVisible(true);
            this.dispose();
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_jLabelRegistrarMouseClicked

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mousex = evt.getX();
        mousey=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void jLabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVolverMouseClicked
        try {
            inicioEmpresa = new InicioEmpresa();
            inicioEmpresa.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(AgregarPlan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelVolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelRegistrar;
    private javax.swing.JLabel jLabelVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegistrar;
    private javax.swing.JPanel jPanelVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparatorName;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextArea txtaDescrip;
    // End of variables declaration//GEN-END:variables
}
