/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Lugares;
import Classes.Usuario;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class InicioAdmin extends javax.swing.JFrame {
    private RegistrarLugar registrarLugar;
    private DefaultTableModel tabla = new DefaultTableModel(){ 
        @Override 
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };         
    private DefaultTableModel tablaUser = new DefaultTableModel(){ 
        @Override 
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    private Lugares myLugares = new Lugares();
    private Usuario myUsuario = new Usuario();
    private Login myLogin = new Login();
    private VerLugar verLugar;
    public static int filaExcel;
    
    
    /**
     * Creates new form InicioAdmin
     */
    public InicioAdmin() throws IOException {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Leer();
        LeerUser();
        this.tableUsuarios.setModel(tablaUser);
        SetImg(Construccion, "src\\IMG\\Proyecto_en_constuccion.jpeg");
        String datos[]= new String[4];
        datos=myUsuario.ObtenerDato(myLogin.ID);
        txtNombreAdmin.setText(datos[0]);
        txtUsuarioAdmin.setText(datos[1]);
        txtPasswordAdmin.setText(datos[2]);
        txtEmailAdmin.setText(datos[3]);
        PanelUsuario.setEnabledAt(0,true);
        PanelUsuario.setEnabledAt(1,false);
        PanelUsuario.setEnabledAt(2,false);
        PanelUsuario.setEnabledAt(3,false);
    }
    
    public void Leer() throws IOException{
        
        int filas = myLugares.nfilas();
        tableLugares.setModel(tabla);
        tabla.addColumn("NOMBRE");
        tabla.addColumn("DIRECCION");
        tabla.addColumn("TIPO");
        tabla.addColumn("HORARIO");
        tabla.addColumn("CALIFICACION");
        String [] confirm = new String[5];
        
        for(int i=1; i<=filas; i++){
            confirm = myLugares.ReadSite(i);
            if (confirm[0] != null) {
                tabla.addRow(confirm);
                
            }
        } 
        
        tableLugares.setModel(tabla);
    }
    
    public void LeerUser() throws IOException{
        int filas = myUsuario.nfilasUser();
        tableUsuarios.setModel(tablaUser);
        tablaUser.addColumn("NOMBRE");
        tablaUser.addColumn("USUARIO");
        tablaUser.addColumn("EMAIL");
        tablaUser.addColumn("NIVEL");
        String [] confirm = new String[4];
        
        for(int i=1; i<=filas; i++){
            confirm = myUsuario.ReadUser(i);
            if (confirm[0] != null) {
                tablaUser.addRow(confirm);
            }
        }
        tableUsuarios.setModel(tablaUser);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horarioLugar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btUsuario = new javax.swing.JButton();
        btEmprezas = new javax.swing.JButton();
        btConfiguracion = new javax.swing.JButton();
        btLugares = new javax.swing.JButton();
        PanelUsuario = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        btnBuscarUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btEliminarUsuario = new javax.swing.JButton();
        btnAscenderUsuario = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btVerLugar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cmbCalificacionLugar = new javax.swing.JComboBox<>();
        btEliminarLugar = new javax.swing.JButton();
        txtNombreLugar = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccionLugar = new javax.swing.JTextField();
        btnBuscarLugar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLugares = new javax.swing.JTable();
        btnAgregarlugar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnDia = new javax.swing.JRadioButton();
        btnNoche = new javax.swing.JRadioButton();
        btn24h = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        btnLimpliar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Construccion = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btActualizar = new javax.swing.JButton();
        btCerrarSesion = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        txtNombreAdmin = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtUsuarioAdmin = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtEmailAdmin = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPasswordAdmin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 0, 0));

        jPanel10.setBackground(new java.awt.Color(255, 228, 196));

        btUsuario.setText("Usuarios");
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });

        btEmprezas.setText("Empresas");
        btEmprezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmprezasActionPerformed(evt);
            }
        });

        btConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/config.png"))); // NOI18N
        btConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracionActionPerformed(evt);
            }
        });

        btLugares.setText("Lugares");
        btLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLugaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(btConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btEmprezas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLugares, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btUsuario)
                .addGap(32, 32, 32)
                .addComponent(btLugares)
                .addGap(36, 36, 36)
                .addComponent(btEmprezas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btConfiguracion)
                .addContainerGap())
        );

        PanelUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 228, 196));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("NOMBRE: ");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("EMAIL: ");

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "USUARIO", "EMAIL ", "NIVEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableUsuarios);

        btnBuscarUsuario.setText("BUSCAR");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("USUARIO: ");

        btEliminarUsuario.setText("ELIMINAR");
        btEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarUsuarioActionPerformed(evt);
            }
        });

        btnAscenderUsuario.setText("ASCENDER");
        btnAscenderUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAscenderUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btnBuscarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnAscenderUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEliminarUsuario)
                        .addGap(272, 272, 272))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarUsuario)
                    .addComponent(btEliminarUsuario)
                    .addComponent(btnAscenderUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelUsuario.addTab("Usuarios", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 228, 196));

        btVerLugar.setText("VER");
        btVerLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerLugarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("CALIFICACION");

        cmbCalificacionLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5" }));

        btEliminarLugar.setText("ELIMINAR");
        btEliminarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarLugarActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("NOMBRE: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DIRECCION");

        btnBuscarLugar.setText("BUSCAR");
        btnBuscarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLugarActionPerformed(evt);
            }
        });

        tableLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "DIRECCION", "TIPO", "CALIFICACCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableLugares);

        btnAgregarlugar.setText("AGREGAR");
        btnAgregarlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarlugarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Horario: ");

        btnDia.setBackground(new java.awt.Color(255, 228, 196));
        horarioLugar.add(btnDia);
        btnDia.setText("Diurno");

        btnNoche.setBackground(new java.awt.Color(255, 228, 196));
        horarioLugar.add(btnNoche);
        btnNoche.setText("Nocturno");

        btn24h.setBackground(new java.awt.Color(255, 228, 196));
        horarioLugar.add(btn24h);
        btn24h.setText("Ambos");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("TIPO:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Centro Comercial", "Parque", "Monumento", "Museo", "Restaurante", "otros" }));

        btnLimpliar.setText("LIMPIAR");
        btnLimpliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnBuscarLugar)
                        .addGap(35, 35, 35)
                        .addComponent(btnAgregarlugar)
                        .addGap(33, 33, 33)
                        .addComponent(btVerLugar)
                        .addGap(27, 27, 27)
                        .addComponent(btEliminarLugar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpliar))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(btnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn24h, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(txtDireccionLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCalificacionLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtNombreLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cmbCalificacionLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccionLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnDia)
                    .addComponent(btn24h)
                    .addComponent(btnNoche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarLugar)
                    .addComponent(btEliminarLugar)
                    .addComponent(btVerLugar)
                    .addComponent(btnAgregarlugar)
                    .addComponent(btnLimpliar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelUsuario.addTab("Lugares", jPanel6);

        jPanel8.setBackground(new java.awt.Color(255, 228, 196));

        Construccion.setText("jLabel4");
        Construccion.setMaximumSize(new java.awt.Dimension(300, 300));
        Construccion.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(Construccion, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(Construccion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        PanelUsuario.addTab("Empresas", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 228, 196));

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        btCerrarSesion.setText("Cerrar Sesion");
        btCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarSesionActionPerformed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setText("DATOS DEL ADMIN");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("NOMBRE:");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("USUARIO:");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("EMAIL: ");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("CLAVE: ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmailAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btActualizar)
                        .addGap(136, 136, 136)
                        .addComponent(btCerrarSesion)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(313, 313, 313))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel32)
                .addGap(46, 46, 46)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtEmailAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtUsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btActualizar)
                    .addComponent(btCerrarSesion))
                .addGap(62, 62, 62))
        );

        PanelUsuario.addTab("Configuracion", jPanel9);

        jPanel2.setBackground(new java.awt.Color(201, 52, 52));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelUsuario)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarlugarActionPerformed
        registrarLugar = new RegistrarLugar();
        registrarLugar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarlugarActionPerformed

    private void btCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarSesionActionPerformed
        myLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCerrarSesionActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        String nombre = txtNombreAdmin.getText(); 
        String usuario = txtUsuarioAdmin.getText();
        String email = txtEmailAdmin.getText();
        String contra= txtPasswordAdmin.getText();
        
        try {
            myUsuario.EditUser(nombre, email, contra, usuario, myLogin.ID, 3);
        } catch (IOException ex) {
            Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
       PanelUsuario.setSelectedIndex(0);
        PanelUsuario.setEnabledAt(0,true);
        PanelUsuario.setEnabledAt(1,false);
        PanelUsuario.setEnabledAt(2,false);
        PanelUsuario.setEnabledAt(3,false);
       
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLugaresActionPerformed
        PanelUsuario.setSelectedIndex(1);
        PanelUsuario.setEnabledAt(1, true);
        PanelUsuario.setEnabledAt(0,false);
        PanelUsuario.setEnabledAt(2,false);
        PanelUsuario.setEnabledAt(3,false);
    }//GEN-LAST:event_btLugaresActionPerformed

    private void btEmprezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmprezasActionPerformed
        PanelUsuario.setSelectedIndex(2);
        PanelUsuario.setEnabledAt(0,false);
        PanelUsuario.setEnabledAt(1,false);
        PanelUsuario.setEnabledAt(2,true);
        PanelUsuario.setEnabledAt(3,false);
    }//GEN-LAST:event_btEmprezasActionPerformed

    private void btConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracionActionPerformed
        PanelUsuario.setSelectedIndex(3);
        PanelUsuario.setEnabledAt(0,false);
        PanelUsuario.setEnabledAt(1,false);
        PanelUsuario.setEnabledAt(2,false);
        PanelUsuario.setEnabledAt(3,true);
        
    }//GEN-LAST:event_btConfiguracionActionPerformed

    private void btVerLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerLugarActionPerformed

        int lugarSeleccionado = tableLugares.getSelectedRow();
        
        if(lugarSeleccionado != -1){
            String nombreSeleccionado = String.valueOf(tableLugares.getModel().getValueAt(lugarSeleccionado, 0));
            String direccionSeleccionada = String.valueOf(tableLugares.getModel().getValueAt(lugarSeleccionado, 1));
            String tipoSeleccionado = String.valueOf(tableLugares.getModel().getValueAt(lugarSeleccionado, 2));
            
            try {
                filaExcel = myLugares.filaSeleccionada(nombreSeleccionado, direccionSeleccionada, tipoSeleccionado);
                verLugar = new VerLugar();
                verLugar.setVisible(true);
                this.setVisible(false);
                
            } catch (IOException ex) {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione de la lista el lugar que desea ver.");
        }
    }//GEN-LAST:event_btVerLugarActionPerformed

    private void btnAscenderUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAscenderUsuarioActionPerformed
        
        String[] confirm = new String[4];
        DefaultTableModel selecUser = tablaUser;
        DefaultTableModel finalUserTable = new DefaultTableModel();
        finalUserTable.addColumn("NOMBRE");
        finalUserTable.addColumn("USUARIO");
        finalUserTable.addColumn("EMAIL");
        finalUserTable.addColumn("NIVEL");
        
        int usuarioSeleccionado = tableUsuarios.getSelectedRow();

        if(usuarioSeleccionado != -1){
            String nombreSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 0));
            String usuSelec = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 1));
            String mailSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 2));

            try {
                filaExcel = myUsuario.filaSeleccionada(nombreSeleccionado, usuSelec, mailSeleccionado);
                
                String [] datosUsu = myUsuario.extraerTodosLosDatos(filaExcel);
                int lvl = Integer.parseInt(datosUsu[4])+1;
                int id = Integer.parseInt(datosUsu[5]);
                int filas = myUsuario.nfilasUser();
                
                myUsuario.EditUser( datosUsu[0], datosUsu[1], datosUsu[2], datosUsu[3], id, lvl);
                
                for(int i=1; i<=filas; i++){
                    confirm = myUsuario.ReadUser(i);
                    if (confirm[0] != null) {
                        finalUserTable.addRow(confirm);
                    }
                }
                tableUsuarios.setModel(finalUserTable);
                JOptionPane.showMessageDialog(null, "Usuario ascendido de maneta satisfactoria.");
                
            } catch (IOException ex) {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione de la lista el usuario que desea ascender.");
        }
    }//GEN-LAST:event_btnAscenderUsuarioActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        
        int j=0;
        String buscar="";
        
        if(txtNombre.getText().isEmpty() && txtEmail.getText().isEmpty()){
            buscar = txtUsuario.getText();
            j=1;
        }else if(txtUsuario.getText().isEmpty() && txtEmail.getText().isEmpty()){
            buscar = txtNombre.getText();
            j=0;
        }else if(txtNombre.getText().isEmpty() && txtUsuario.getText().isEmpty()){
            buscar = txtEmail.getText();
            j=2;
        }
        
        
        for (int i=0; i<tablaUser.getRowCount(); i++){
            if(tablaUser.getValueAt(i, j).toString().matches(".*"+buscar+".*")){
                tableUsuarios.changeSelection(i, j, false, false);
            }
        }   
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarUsuarioActionPerformed

        DefaultTableModel selecUser = tablaUser;
        
        int usuarioSeleccionado = tableUsuarios.getSelectedRow();
        if(usuarioSeleccionado != -1){
            String nombreSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 0));
            String usuSelec = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 1));
            String mailSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 2));

            try {
                int excelFill = myUsuario.filaSeleccionada(nombreSeleccionado, usuSelec, mailSeleccionado);
                myUsuario.DeleteUser(excelFill);    

             } catch (IOException ex) {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            if(usuarioSeleccionado>=0){
            tablaUser.removeRow(usuarioSeleccionado);
            tableUsuarios.setModel(tablaUser);
            }
            else{
                JOptionPane.showMessageDialog(null, "No ha seleccionado fila");
            }
        }
    }//GEN-LAST:event_btEliminarUsuarioActionPerformed
   
    
    private void btnBuscarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLugarActionPerformed
        String buscar="";
        int j=0;
        String hora=" ";
        String []aux = new String[5];
        
        DefaultTableModel tablaaux = new DefaultTableModel();
        tablaaux.addColumn("NOMBRE");
        tablaaux.addColumn("DIRECCION");
        tablaaux.addColumn("TIPO"); 
        tablaaux.addColumn("HORARIO");
        tablaaux.addColumn("CALIFICACION");
        
        
        
        String calificacion = (String)cmbCalificacionLugar.getSelectedItem();
        String tipo = (String)cmbTipo.getSelectedItem();
        
        if(btnDia.isSelected()){
            hora="Diurno";
        }else if(btnNoche.isSelected()){
            hora="Nocturno";
        }else if(btn24h.isSelected()){
            hora="24 horas";
        }
        
        if(txtNombreLugar.getText().isEmpty() && calificacion.equals(" ") && tipo.equals(" ") && hora.equals(" ")){
            buscar = txtDireccionLugar.getText();
            j=1;
            
        }else if(txtDireccionLugar.getText().isEmpty() && calificacion.equals(" ") && tipo.equals(" ")&& hora.equals(" ")){
            buscar = txtNombreLugar.getText();
            j=0;
            
        }else if(txtNombreLugar.getText().isEmpty() && txtDireccionLugar.getText().isEmpty() && tipo.equals(" ")&& hora.equals(" ")){
            buscar=calificacion;
            j=4;
            
        }else if(txtNombreLugar.getText().isEmpty() && txtDireccionLugar.getText().isEmpty() && calificacion.equals(" ")&& hora.equals(" ")){
            buscar=tipo;
            j=2;
            
        }else if(txtNombreLugar.getText().isEmpty() && txtDireccionLugar.getText().isEmpty() && calificacion.equals(" ")&& tipo.equals(" ")){
            buscar=hora;    
            j=3;
        }
        
        
        for (int i=0; i<tabla.getRowCount(); i++){
              
                if(tabla.getValueAt(i, j).toString().matches(".*"+buscar+".*")){
                    for(int h=0; h<=4 ;h++){
                        aux[h]=(String)tabla.getValueAt(i, h);
                    }
                        tablaaux.addRow(aux);
                        tableLugares.changeSelection(i, j, false, false);
                }
          
        }
        tableLugares.setModel(tablaaux);
        
        
    }//GEN-LAST:event_btnBuscarLugarActionPerformed

    private void btnLimpliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpliarActionPerformed
        txtNombreLugar.setText("");
        txtDireccionLugar.setText("");
        cmbCalificacionLugar.setSelectedIndex(0);
        cmbTipo.setSelectedIndex(0);
        horarioLugar.clearSelection();
        tableLugares.setModel(tabla);
        
    }//GEN-LAST:event_btnLimpliarActionPerformed

    private void btEliminarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarLugarActionPerformed
        DefaultTableModel selecUser = tabla;
        
        int usuarioSeleccionado = tableLugares.getSelectedRow();
        
        if(usuarioSeleccionado != -1){
            String nombreSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 0));
            String usuSelec = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 1));
            String mailSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 2));

            try {
                int excelFill = myLugares.filaSeleccionada(nombreSeleccionado, usuSelec, mailSeleccionado);
                myLugares.deleteSite(excelFill);    

             } catch (IOException ex) {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            if(usuarioSeleccionado>=0){
            tabla.removeRow(usuarioSeleccionado);
            }
            else{
                JOptionPane.showMessageDialog(null, "No ha seleccionado fila");
            }
        }
    }//GEN-LAST:event_btEliminarLugarActionPerformed
    
    
        
    
    
    private void SetImg(JLabel labelName, String ruta){
        ImageIcon image = new ImageIcon(ruta);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InicioAdmin().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InicioAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Construccion;
    private javax.swing.JTabbedPane PanelUsuario;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btConfiguracion;
    private javax.swing.JButton btEliminarLugar;
    private javax.swing.JButton btEliminarUsuario;
    private javax.swing.JButton btEmprezas;
    private javax.swing.JButton btLugares;
    private javax.swing.JButton btUsuario;
    private javax.swing.JButton btVerLugar;
    private javax.swing.JRadioButton btn24h;
    private javax.swing.JButton btnAgregarlugar;
    private javax.swing.JButton btnAscenderUsuario;
    private javax.swing.JButton btnBuscarLugar;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JRadioButton btnDia;
    private javax.swing.JButton btnLimpliar;
    private javax.swing.JRadioButton btnNoche;
    private javax.swing.JComboBox<String> cmbCalificacionLugar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.ButtonGroup horarioLugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tableLugares;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JTextField txtDireccionLugar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailAdmin;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreAdmin;
    private javax.swing.JTextField txtNombreLugar;
    private javax.swing.JTextField txtPasswordAdmin;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioAdmin;
    // End of variables declaration//GEN-END:variables
}
