/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Empresas;
import Classes.Lugares;
import Classes.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class InicioAdmin extends javax.swing.JFrame {
    int mousex, mousey;
    
    private RegistrarLugar registrarLugar;
    
    private DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private DefaultTableModel tablaUser = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private DefaultTableModel tablaEmpresas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private Lugares myLugares = new Lugares();
    private Usuario myUsuario = new Usuario();
    private Empresas myEmpresas = new Empresas();
    private NewLogin myLogin = new NewLogin();
    private VerLugar verLugar;
    public static int indexExcel;

    /**
     * Creates new form InicioAdmin
     */
    public InicioAdmin() throws IOException {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Leer();
        LeerUser();
        LeerEmpresas();
        String datos[] = new String[4];
        datos = myUsuario.ObtenerDato(myLogin.ID);
        txtNombreAdmin.setText(datos[0]);
        txtUsuarioAdmin.setText(datos[1]);
        txtPasswordAdmin.setText(datos[2]);
        txtEmailAdmin.setText(datos[3]);
        PanelUsuario.setEnabledAt(0, true);
        PanelUsuario.setEnabledAt(1, false);
        PanelUsuario.setEnabledAt(2, false);
        PanelUsuario.setEnabledAt(3, false);
    }

    public void Leer() throws IOException {

        int filas = myLugares.nfilas();
        tabla.addColumn("NOMBRE");
        tabla.addColumn("DIRECCION");
        tabla.addColumn("TIPO");
        tabla.addColumn("HORARIO");
        tabla.addColumn("CALIFICACION");
        String[] confirm = new String[5];

        for (int i = 1; i <= filas; i++)
        {
            confirm = myLugares.ReadSite(i);
            if (confirm[0] != null)
            {
                tabla.addRow(confirm);

            }
        }
        tableLugares.setModel(tabla);
    }

    public void LeerUser() throws IOException {
        int filas = myUsuario.nfilasUser();
        tablaUser.addColumn("NOMBRE");
        tablaUser.addColumn("USUARIO");
        tablaUser.addColumn("EMAIL");
        tablaUser.addColumn("NIVEL");
        String[] confirm = new String[4];

        for (int i = 1; i <= filas; i++){
            
            confirm = myUsuario.ReadUser(i);
            if (confirm[0] != null){
                
                tablaUser.addRow(confirm);
            }
        }
        tableUsuarios.setModel(tablaUser);
    }
    
    
    // Se debe de los metodos del myLugares, con un objeto tipo empresa y Usar los mismo metodos, se pueden copiar y pegar esos metodos a la clase empresa
    //Los metodos son los de nfilas y ReadSite
    
    public void LeerEmpresas() throws IOException {

        int filas = myLugares.nfilas();
        tablaEmpresas.addColumn("RAZON SOCIAL");
        tablaEmpresas.addColumn("USUARIO");
        tablaEmpresas.addColumn("NIT");
        tablaEmpresas.addColumn("EMAIL");
        String[] confirm = new String[4];

        for (int i = 1; i <= filas; i++)
        {
            confirm = myEmpresas.ReadEnterprise(i);
            if (confirm[0] != null)
            {
                tablaEmpresas.addRow(confirm);

            }
        }
        tableEmpresas.setModel(tablaEmpresas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horarioLugar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnUsuario = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        BtnLugares = new javax.swing.JPanel();
        Lugares = new javax.swing.JLabel();
        BtnEmpresa = new javax.swing.JPanel();
        Empresas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btConfiguracion = new javax.swing.JButton();
        PanelUsuario = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        btnBuscarUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btEliminarUsuario = new javax.swing.JButton();
        btnAscenderUsuario = new javax.swing.JButton();
        btnDesenderUsuario = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btVerLugar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cmbCalificacionLugar = new javax.swing.JComboBox<>();
        btEliminarLugar = new javax.swing.JButton();
        txtNombreLugar = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccionLugar = new javax.swing.JTextField();
        btnBuscarLugar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLugares = new javax.swing.JTable();
        btnAgregarlugar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnDia = new javax.swing.JRadioButton();
        btnNoche = new javax.swing.JRadioButton();
        btn24h = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        btnLimpliar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        txtEmailEmpresa = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableEmpresas = new javax.swing.JTable();
        btnBuscarEmpresa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        btEliminarEmpresa = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtUsuarioEmpresa = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btActualizar = new javax.swing.JButton();
        btCerrarSesion = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        txtNombreAdmin = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtUsuarioAdmin = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtEmailAdmin = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPasswordAdmin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 245, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setForeground(new java.awt.Color(255, 121, 121));
        Header.setOpaque(false);
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 50));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCloseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtCerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCloseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtCerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 60, -1));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LogoNew.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel4.setText("Motiviator");

        BtnUsuario.setBackground(new java.awt.Color(204, 204, 204));
        BtnUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnUsuario.setForeground(new java.awt.Color(255, 102, 102));
        BtnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUsuarioMouseClicked(evt);
            }
        });

        Usuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ImgUsuarios.png"))); // NOI18N
        Usuario.setText("\n\nUsuarios");

        javax.swing.GroupLayout BtnUsuarioLayout = new javax.swing.GroupLayout(BtnUsuario);
        BtnUsuario.setLayout(BtnUsuarioLayout);
        BtnUsuarioLayout.setHorizontalGroup(
            BtnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        BtnUsuarioLayout.setVerticalGroup(
            BtnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        BtnLugares.setBackground(new java.awt.Color(204, 204, 204));
        BtnLugares.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnLugares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLugaresMouseClicked(evt);
            }
        });

        Lugares.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Lugares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ImgLugares.png"))); // NOI18N
        Lugares.setText("Lugares");
        Lugares.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BtnLugaresLayout = new javax.swing.GroupLayout(BtnLugares);
        BtnLugares.setLayout(BtnLugaresLayout);
        BtnLugaresLayout.setHorizontalGroup(
            BtnLugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lugares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        BtnLugaresLayout.setVerticalGroup(
            BtnLugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lugares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        BtnEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        BtnEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEmpresaMouseClicked(evt);
            }
        });

        Empresas.setBackground(new java.awt.Color(204, 204, 204));
        Empresas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Empresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgenterprise.png"))); // NOI18N
        Empresas.setText("Empresas");
        Empresas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BtnEmpresaLayout = new javax.swing.GroupLayout(BtnEmpresa);
        BtnEmpresa.setLayout(BtnEmpresaLayout);
        BtnEmpresaLayout.setHorizontalGroup(
            BtnEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Empresas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        BtnEmpresaLayout.setVerticalGroup(
            BtnEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Empresas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btConfiguracion.setBackground(new java.awt.Color(204, 204, 204));
        btConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/config.png"))); // NOI18N
        btConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnLugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BtnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(BtnLugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(BtnEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btConfiguracion)
                .addGap(34, 34, 34))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 593));

        PanelUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(217, 152, 141));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel31.setText("NOMBRE: ");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel33.setText("EMAIL: ");

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String [] {
                "NOMBRE", "USUARIO", "EMAIL ", "NIVEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableUsuarios);

        btnBuscarUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgsearch.png"))); // NOI18N
        btnBuscarUsuario.setText("Buscar");
        btnBuscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("USUARIO: ");

        btEliminarUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgeliminar.png"))); // NOI18N
        btEliminarUsuario.setText("Eliminar");
        btEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarUsuarioActionPerformed(evt);
            }
        });

        btnAscenderUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAscenderUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgascender.png"))); // NOI18N
        btnAscenderUsuario.setText("Ascender");
        btnAscenderUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAscenderUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAscenderUsuarioActionPerformed(evt);
            }
        });

        btnDesenderUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnDesenderUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgdescender.png"))); // NOI18N
        btnDesenderUsuario.setText("Descender");
        btnDesenderUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDesenderUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesenderUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAscenderUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesenderUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAscenderUsuario)
                    .addComponent(btnDesenderUsuario)
                    .addComponent(btnBuscarUsuario)
                    .addComponent(btEliminarUsuario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        PanelUsuario.addTab("Usuarios", jPanel5);

        jPanel6.setBackground(new java.awt.Color(217, 152, 141));

        btVerLugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ImgVer.png"))); // NOI18N
        btVerLugar.setText("Ver");
        btVerLugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVerLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerLugarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("CALIFICACION");

        cmbCalificacionLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5" }));

        btEliminarLugar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btEliminarLugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgeliminar.png"))); // NOI18N
        btEliminarLugar.setText("Eliminar");
        btEliminarLugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEliminarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarLugarActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("NOMBRE: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DIRECCION");

        btnBuscarLugar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscarLugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgsearch.png"))); // NOI18N
        btnBuscarLugar.setText("Buscar");
        btnBuscarLugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLugarActionPerformed(evt);
            }
        });

        tableLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "DIRECCION", "TIPO", "CALIFICACCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableLugares);

        btnAgregarlugar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAgregarlugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ImgAgregar.png"))); // NOI18N
        btnAgregarlugar.setText("Agregar");
        btnAgregarlugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarlugarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Horario: ");

        btnDia.setBackground(new java.awt.Color(217, 152, 141));
        horarioLugar.add(btnDia);
        btnDia.setText("Diurno");

        btnNoche.setBackground(new java.awt.Color(217, 152, 141));
        horarioLugar.add(btnNoche);
        btnNoche.setText("Nocturno");

        btn24h.setBackground(new java.awt.Color(217, 152, 141));
        horarioLugar.add(btn24h);
        btn24h.setText("Ambos");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("TIPO:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Centro Comercial", "Parque", "Monumento", "Museo", "Restaurante", "otros" }));

        btnLimpliar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnLimpliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imglimpiar.png"))); // NOI18N
        btnLimpliar.setText("Limpiar");
        btnLimpliar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(txtDireccionLugar)
                .addGap(39, 39, 39)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCalificacionLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBuscarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarlugar)
                        .addGap(18, 18, 18)
                        .addComponent(btVerLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEliminarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpliar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(44, 44, 44)
                        .addComponent(btnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn24h, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel21)
                        .addGap(27, 27, 27)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtNombreLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cmbCalificacionLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccionLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnDia)
                    .addComponent(btn24h)
                    .addComponent(btnNoche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarlugar)
                    .addComponent(btVerLugar)
                    .addComponent(btnBuscarLugar)
                    .addComponent(btEliminarLugar)
                    .addComponent(btnLimpliar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelUsuario.addTab("Lugares", jPanel6);

        jPanel7.setBackground(new java.awt.Color(217, 152, 141));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel35.setText("RAZON SOCIAL: ");

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel36.setText("EMAIL: ");

        tableEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String [] {
                "NOMBRE", "USUARIO", "EMAIL ", "NIVEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tableEmpresas);

        btnBuscarEmpresa.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgsearch.png"))); // NOI18N
        btnBuscarEmpresa.setText("Buscar");
        btnBuscarEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpresaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("NIT:");

        btEliminarEmpresa.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btEliminarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgeliminar.png"))); // NOI18N
        btEliminarEmpresa.setText("Eliminar");
        btEliminarEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEliminarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarEmpresaActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel37.setText("USUARIO: ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel37))
                            .addComponent(btnBuscarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(btEliminarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(txtEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(txtUsuarioEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEmpresa)
                    .addComponent(btEliminarEmpresa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        PanelUsuario.addTab("Empresas", jPanel7);

        jPanel9.setBackground(new java.awt.Color(217, 152, 141));

        btActualizar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imgactualizar.png"))); // NOI18N
        btActualizar.setText("Actualizar");
        btActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        btCerrarSesion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ImgCerrar.png"))); // NOI18N
        btCerrarSesion.setText("Cerrar Sesion");
        btCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarSesionActionPerformed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setText("DATOS DEL ADMIN");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("NOMBRE:");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("USUARIO:");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("EMAIL: ");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("CLAVE: ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(313, 313, 313))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(btCerrarSesion)
                        .addGap(193, 193, 193))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel32)
                .addGap(46, 46, 46)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtEmailAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtUsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCerrarSesion)
                    .addComponent(btActualizar))
                .addGap(138, 138, 138))
        );

        PanelUsuario.addTab("Configuracion", jPanel9);

        jPanel1.add(PanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 880, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/939716.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 900, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarlugarActionPerformed
        registrarLugar = new RegistrarLugar();
        registrarLugar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarlugarActionPerformed

    private void btCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarSesionActionPerformed
        myLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCerrarSesionActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        String nombre = txtNombreAdmin.getText();
        String usuario = txtUsuarioAdmin.getText();
        String email = txtEmailAdmin.getText();
        String contra = txtPasswordAdmin.getText();

        try
        {
            myUsuario.EditUser(nombre, usuario, contra, email, myLogin.ID, 3);
        } catch (IOException ex)
        {
            Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracionActionPerformed
        PanelUsuario.setSelectedIndex(3);
        PanelUsuario.setEnabledAt(0, false);
        PanelUsuario.setEnabledAt(1, false);
        PanelUsuario.setEnabledAt(2, false);
        PanelUsuario.setEnabledAt(3, true);

    }//GEN-LAST:event_btConfiguracionActionPerformed

    private void btVerLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerLugarActionPerformed

        int lugarSeleccionado = tableLugares.getSelectedRow();

        if (lugarSeleccionado != -1)
        {
            String nombreSeleccionado = String.valueOf(tableLugares.getModel().getValueAt(lugarSeleccionado, 0));
            String direccionSeleccionada = String.valueOf(tableLugares.getModel().getValueAt(lugarSeleccionado, 1));
            String tipoSeleccionado = String.valueOf(tableLugares.getModel().getValueAt(lugarSeleccionado, 2));

            try
            {
                indexExcel = myLugares.filaSeleccionada(nombreSeleccionado, direccionSeleccionada, tipoSeleccionado);
                verLugar = new VerLugar();
                verLugar.setVisible(true);
                this.setVisible(false);

            } catch (IOException ex)
            {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Seleccione de la lista el lugar que desea ver.");
        }
    }//GEN-LAST:event_btVerLugarActionPerformed

    private void btnAscenderUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAscenderUsuarioActionPerformed

        String[] confirm = new String[4];
        DefaultTableModel selecUser = tablaUser;
        DefaultTableModel finalUserTable = new DefaultTableModel();
        finalUserTable.addColumn("NOMBRE");
        finalUserTable.addColumn("USUARIO");
        finalUserTable.addColumn("EMAIL");
        finalUserTable.addColumn("NIVEL");

        int usuarioSeleccionado = tableUsuarios.getSelectedRow();

        if (usuarioSeleccionado != -1)
        {
            String nombreSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 0));
            String usuSelec = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 1));
            String mailSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 2));
            try
            {
                indexExcel = myUsuario.filaSeleccionada(nombreSeleccionado, usuSelec, mailSeleccionado);
                String[] datosUsu = myUsuario.extraerTodosLosDatos(indexExcel);
                if (Integer.parseInt(datosUsu[4]) == 3)
                {
                    JOptionPane.showMessageDialog(null, "El usuario ya es un admin no se puede acender mas");
                } else
                {
                    int lvl = Integer.parseInt(datosUsu[4]) + 1;
                    int id = Integer.parseInt(datosUsu[5]);
                    int filas = myUsuario.nfilasUser();

                    myUsuario.EditUser(datosUsu[0], datosUsu[1], datosUsu[2], datosUsu[3], id, lvl);

                    for (int i = 1; i <= filas; i++)
                    {
                        confirm = myUsuario.ReadUser(i);
                        if (confirm[0] != null)
                        {
                            finalUserTable.addRow(confirm);
                        }
                    }
                    tableUsuarios.setModel(finalUserTable);
                    JOptionPane.showMessageDialog(null, "Usuario ascendido de manera satisfactoria.");
                }

            } catch (IOException ex)
            {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Seleccione de la lista el usuario que desea ascender.");
        }
    }//GEN-LAST:event_btnAscenderUsuarioActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed

        int j = 0;
        String buscar = "";

        if (txtNombre.getText().isEmpty() && txtEmail.getText().isEmpty())
        {
            buscar = txtUsuario.getText();
            j = 1;
        } else if (txtUsuario.getText().isEmpty() && txtEmail.getText().isEmpty())
        {
            buscar = txtNombre.getText();
            j = 0;
        } else if (txtNombre.getText().isEmpty() && txtUsuario.getText().isEmpty())
        {
            buscar = txtEmail.getText();
            j = 2;
        }

        buscar = buscar.toLowerCase(); // Convertir cadena de búsqueda a minúsculas

        for (int i = 0; i < tablaUser.getRowCount(); i++)
        {
            String valorTabla = tablaUser.getValueAt(i, j).toString().toLowerCase(); // Convertir valor de la tabla a minúsculas
            if (valorTabla.matches(".*" + buscar + ".*"))
            {
                tableUsuarios.changeSelection(i, j, false, false);
            }
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarUsuarioActionPerformed

        DefaultTableModel selecUser = tablaUser;

        int usuarioSeleccionado = tableUsuarios.getSelectedRow();
        if (usuarioSeleccionado != -1)
        {
            String nombreSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 0));
            String usuSelec = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 1));
            String mailSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 2));

            try
            {
                int excelFill = myUsuario.filaSeleccionada(nombreSeleccionado, usuSelec, mailSeleccionado);
                myUsuario.DeleteUser(excelFill);

            } catch (IOException ex)
            {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (usuarioSeleccionado >= 0)
            {
                tablaUser.removeRow(usuarioSeleccionado);
                tableUsuarios.setModel(tablaUser);
            } else
            {
                JOptionPane.showMessageDialog(null, "No ha seleccionado fila");
            }
        }
    }//GEN-LAST:event_btEliminarUsuarioActionPerformed


    private void btnBuscarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLugarActionPerformed
        String buscar = "";
        int j = 0;
        String hora = " ";
        String[] aux = new String[5];

        DefaultTableModel tablaaux = new DefaultTableModel();
        tablaaux.addColumn("NOMBRE");
        tablaaux.addColumn("DIRECCION");
        tablaaux.addColumn("TIPO");
        tablaaux.addColumn("HORARIO");
        tablaaux.addColumn("CALIFICACION");

        String calificacion = (String) cmbCalificacionLugar.getSelectedItem();
        String tipo = (String) cmbTipo.getSelectedItem();

        if (btnDia.isSelected())
        {
            hora = "Diurno";
        } else if (btnNoche.isSelected())
        {
            hora = "Nocturno";
        } else if (btn24h.isSelected())
        {
            hora = "24 horas";
        }

        if (txtNombreLugar.getText().isEmpty() && calificacion.equals(" ") && tipo.equals(" ") && hora.equals(" "))
        {
            buscar = txtDireccionLugar.getText();
            j = 1;
        } else if (txtDireccionLugar.getText().isEmpty() && calificacion.equals(" ") && tipo.equals(" ") && hora.equals(" "))
        {
            buscar = txtNombreLugar.getText();
            j = 0;
        } else if (txtNombreLugar.getText().isEmpty() && txtDireccionLugar.getText().isEmpty() && tipo.equals(" ") && hora.equals(" "))
        {
            buscar = calificacion;
            j = 4;
        } else if (txtNombreLugar.getText().isEmpty() && txtDireccionLugar.getText().isEmpty() && calificacion.equals(" ") && hora.equals(" "))
        {
            buscar = tipo;
            j = 2;
        } else if (txtNombreLugar.getText().isEmpty() && txtDireccionLugar.getText().isEmpty() && calificacion.equals(" ") && tipo.equals(" "))
        {
            buscar = hora;
            j = 3;
        }

        for (int i = 0; i < tabla.getRowCount(); i++)
        {
            String valor = tabla.getValueAt(i, j).toString().toLowerCase();
            if (valor.contains(buscar.toLowerCase()))
            {
                for (int h = 0; h <= 4; h++)
                {
                    aux[h] = tabla.getValueAt(i, h).toString();
                }
                tablaaux.addRow(aux);
                tableLugares.changeSelection(i, j, false, false);
            }
        }

        tableLugares.setModel(tablaaux);
    }//GEN-LAST:event_btnBuscarLugarActionPerformed

    private void btnLimpliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpliarActionPerformed
        txtNombreLugar.setText("");
        txtDireccionLugar.setText("");
        cmbCalificacionLugar.setSelectedIndex(0);
        cmbTipo.setSelectedIndex(0);
        horarioLugar.clearSelection();
        tableLugares.setModel(tabla);

    }//GEN-LAST:event_btnLimpliarActionPerformed

    private void btEliminarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarLugarActionPerformed
        DefaultTableModel selecUser = tabla;

        int usuarioSeleccionado = tableLugares.getSelectedRow();

        if (usuarioSeleccionado != -1)
        {
            String nombreSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 0));
            String usuSelec = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 1));
            String mailSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 2));

            try
            {
                int excelFill = myLugares.filaSeleccionada(nombreSeleccionado, usuSelec, mailSeleccionado);
                myLugares.deleteSite(excelFill);

            } catch (IOException ex)
            {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (usuarioSeleccionado >= 0)
            {
                tabla.removeRow(usuarioSeleccionado);
            } else
            {
                JOptionPane.showMessageDialog(null, "No ha seleccionado fila");
            }
        }
    }//GEN-LAST:event_btEliminarLugarActionPerformed

    private void btnDesenderUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesenderUsuarioActionPerformed

        String[] confirm = new String[4];
        DefaultTableModel selecUser = tablaUser;
        DefaultTableModel finalUserTable = new DefaultTableModel();
        finalUserTable.addColumn("NOMBRE");
        finalUserTable.addColumn("USUARIO");
        finalUserTable.addColumn("EMAIL");
        finalUserTable.addColumn("NIVEL");

        int usuarioSeleccionado = tableUsuarios.getSelectedRow();

        if (usuarioSeleccionado != -1)
        {
            String nombreSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 0));
            String usuSelec = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 1));
            String mailSeleccionado = String.valueOf(selecUser.getValueAt(usuarioSeleccionado, 2));
            try
            {
                indexExcel = myUsuario.filaSeleccionada(nombreSeleccionado, usuSelec, mailSeleccionado);
                String[] datosUsu = myUsuario.extraerTodosLosDatos(indexExcel);
                if (Integer.parseInt(datosUsu[4]) == 1)
                {
                    JOptionPane.showMessageDialog(null, "no se puede desenser usuraio");
                } else
                {
                    int lvl = Integer.parseInt(datosUsu[4]) - 1;
                    int id = Integer.parseInt(datosUsu[5]);
                    int filas = myUsuario.nfilasUser();

                    myUsuario.EditUser(datosUsu[0], datosUsu[1], datosUsu[2], datosUsu[3], id, lvl);

                    for (int i = 1; i <= filas; i++)
                    {
                        confirm = myUsuario.ReadUser(i);
                        if (confirm[0] != null)
                        {
                            finalUserTable.addRow(confirm);
                        }
                    }
                    tableUsuarios.setModel(finalUserTable);
                    JOptionPane.showMessageDialog(null, "Usuario desensido de mareta satisfactoria.");
                }

            } catch (IOException ex)
            {
                Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Seleccione de la lista el usuario que desea ascender.");
        }
    }//GEN-LAST:event_btnDesenderUsuarioActionPerformed

    private void BtnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUsuarioMouseClicked
        PanelUsuario.setSelectedIndex(0);
        PanelUsuario.setEnabledAt(0, true);
        PanelUsuario.setEnabledAt(1, false);
        PanelUsuario.setEnabledAt(2, false);
        PanelUsuario.setEnabledAt(3, false);
    }//GEN-LAST:event_BtnUsuarioMouseClicked

    private void BtnLugaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLugaresMouseClicked
        PanelUsuario.setSelectedIndex(1);
        PanelUsuario.setEnabledAt(1, true);
        PanelUsuario.setEnabledAt(0, false);
        PanelUsuario.setEnabledAt(2, false);
        PanelUsuario.setEnabledAt(3, false);
    }//GEN-LAST:event_BtnLugaresMouseClicked

    private void BtnEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpresaMouseClicked
        PanelUsuario.setSelectedIndex(2);
        PanelUsuario.setEnabledAt(0, false);
        PanelUsuario.setEnabledAt(1, false);
        PanelUsuario.setEnabledAt(2, true);
        PanelUsuario.setEnabledAt(3, false);
    }//GEN-LAST:event_BtnEmpresaMouseClicked

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mousex = evt.getX();
        mousey=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void btnBuscarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEmpresaActionPerformed

    private void btEliminarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEliminarEmpresaActionPerformed

    private void SetImg(JLabel labelName, String ruta) {
        ImageIcon image = new ImageIcon(ruta);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    new InicioAdmin().setVisible(true);
                } catch (IOException ex)
                {
                    Logger.getLogger(InicioAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnEmpresa;
    private javax.swing.JPanel BtnLugares;
    private javax.swing.JPanel BtnUsuario;
    private javax.swing.JLabel Empresas;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Lugares;
    private javax.swing.JTabbedPane PanelUsuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btConfiguracion;
    private javax.swing.JButton btEliminarEmpresa;
    private javax.swing.JButton btEliminarLugar;
    private javax.swing.JButton btEliminarUsuario;
    private javax.swing.JButton btVerLugar;
    private javax.swing.JRadioButton btn24h;
    private javax.swing.JButton btnAgregarlugar;
    private javax.swing.JButton btnAscenderUsuario;
    private javax.swing.JButton btnBuscarEmpresa;
    private javax.swing.JButton btnBuscarLugar;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JPanel btnClose;
    private javax.swing.JButton btnDesenderUsuario;
    private javax.swing.JRadioButton btnDia;
    private javax.swing.JButton btnLimpliar;
    private javax.swing.JRadioButton btnNoche;
    private javax.swing.JComboBox<String> cmbCalificacionLugar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.ButtonGroup horarioLugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tableEmpresas;
    private javax.swing.JTable tableLugares;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JLabel txtCerrar;
    private javax.swing.JTextField txtDireccionLugar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailAdmin;
    private javax.swing.JTextField txtEmailEmpresa;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreAdmin;
    private javax.swing.JTextField txtNombreLugar;
    private javax.swing.JTextField txtPasswordAdmin;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioAdmin;
    private javax.swing.JTextField txtUsuarioEmpresa;
    // End of variables declaration//GEN-END:variables
}
