/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Empresas;
import Classes.PlanesTuristicos;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josem
 */
public class VerEmpresa extends javax.swing.JFrame {
    int mousex, mousey;
    
    private DefaultTableModel tablaPlanes = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private static Empresas theEmpresa;
    private InicioAdmin myAdmin;
    private InicioUsuario myUsuario;
    private InicioEmpresa myEmpresa;
    private String nameEmpresa;
    private String mailEmpresa;
    private String descripcion;
    private PlanesTuristicos myPlans;
    
    public VerEmpresa() throws IOException {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        if (NewLogin.level == 3){
            setDatos(myAdmin.filaExcel);
        }
        else if(NewLogin.level == 2 || NewLogin.level ==1){
            setDatos(myUsuario.filaExcel);
        }
        Nombre.setText(nameEmpresa);
        Email.setText(mailEmpresa);
        txtaDescrip.setText(descripcion);
        Leer();
    }
    
    public void setDatos(int filaExcel){
        String info[] = new String[3];
        info = theEmpresa.ObtenerDato(filaExcel);
        nameEmpresa= info[0];
        mailEmpresa = info[4];
        descripcion = info[5];
    }
    
    public void Leer() throws IOException {

        int filas = myPlans.nfilas(nameEmpresa);
        if(filas!=0){
            tablaPlanes.addColumn("NOMBRE");
            tablaPlanes.addColumn("DESCRIPCION");
            tablaPlanes.addColumn("PRECIO");
            String[] confirm = new String[3];

            for (int i = 1; i <= filas; i++){
                confirm = myPlans.ReadPlan(i,nameEmpresa);
                if (confirm[0] != null){
                    tablaPlanes.addRow(confirm);
                }
            }
            tablePlanes.setModel(tablaPlanes);
        }else{
            JOptionPane.showMessageDialog(null, nameEmpresa+" aun no tiene planes creados para usted");
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePlanes = new javax.swing.JTable();
        PestañaAnterios = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        btnVerDescripcion = new javax.swing.JPanel();
        btnVerDescrip = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaDescrip = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Planes Turisticos:");
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        Email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Email.setText("\"Email\"");
        BackGround.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FondoPlanTuristico1.png"))); // NOI18N
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 540));

        tablePlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePlanes);

        BackGround.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 560, 230));

        PestañaAnterios.setBackground(new java.awt.Color(204, 204, 204));
        PestañaAnterios.setPreferredSize(new java.awt.Dimension(138, 67));

        btnVolver.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ImgVolver.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PestañaAnteriosLayout = new javax.swing.GroupLayout(PestañaAnterios);
        PestañaAnterios.setLayout(PestañaAnteriosLayout);
        PestañaAnteriosLayout.setHorizontalGroup(
            PestañaAnteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        PestañaAnteriosLayout.setVerticalGroup(
            PestañaAnteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        BackGround.add(PestañaAnterios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 150, 70));

        btnVerDescripcion.setBackground(new java.awt.Color(204, 204, 204));
        btnVerDescripcion.setPreferredSize(new java.awt.Dimension(138, 67));

        btnVerDescrip.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnVerDescrip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVerDescrip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ImgVer.png"))); // NOI18N
        btnVerDescrip.setText("Ver Descripcion");
        btnVerDescrip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerDescrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerDescripMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnVerDescripcionLayout = new javax.swing.GroupLayout(btnVerDescripcion);
        btnVerDescripcion.setLayout(btnVerDescripcionLayout);
        btnVerDescripcionLayout.setHorizontalGroup(
            btnVerDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVerDescrip, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnVerDescripcionLayout.setVerticalGroup(
            btnVerDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVerDescrip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        BackGround.add(btnVerDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 150, 70));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Descripcion: ");
        BackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setToolTipText("");

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar)
        );

        BackGround.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, -1));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Nombre.setText("\"nombre\"");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(Nombre)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(Nombre))
        );

        BackGround.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 40));

        txtaDescrip.setEditable(false);
        txtaDescrip.setColumns(20);
        txtaDescrip.setLineWrap(true);
        txtaDescrip.setRows(5);
        jScrollPane3.setViewportView(txtaDescrip);

        BackGround.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 560, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        if (NewLogin.level == 3){
            try {
                this.myAdmin = new InicioAdmin();
                myAdmin.setVisible(true);
                this.dispose();
            }
            catch (Exception ex) {
                
            }
        }
        else if(NewLogin.level == 2 || NewLogin.level == 1){
            try {
                this.myUsuario = new InicioUsuario();
            } catch (IOException ex) {
                Logger.getLogger(VerEmpresa.class.getName()).log(Level.SEVERE, null, ex);
            }
            myUsuario.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVerDescripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerDescripMouseClicked
        int seleccion = tablePlanes.getSelectedRow();
        
        if(seleccion != -1){
            String mensaje = String.valueOf(tablePlanes.getModel().getValueAt(seleccion, 1));
            JOptionPane.showMessageDialog(null,mensaje);
        }else{
            JOptionPane.showMessageDialog(null,"Primero seleccione un plan");
        }
    }//GEN-LAST:event_btnVerDescripMouseClicked

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.white);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mousex = evt.getX();
        mousey=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VerEmpresa().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VerEmpresa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel Email;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel PestañaAnterios;
    private javax.swing.JPanel btnClose;
    private javax.swing.JLabel btnVerDescrip;
    private javax.swing.JPanel btnVerDescripcion;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablePlanes;
    private javax.swing.JLabel txtCerrar;
    private javax.swing.JTextArea txtaDescrip;
    // End of variables declaration//GEN-END:variables
}
